### ISSUE TITLE
Bullet Count Graphical Glitch

### ISSUE THREAD

**Issue by SamuraiScientist** [GreatBigBushyBeard/PAYDAY-2-PDTH-Hud#2]
Sometimes the HUD will glitch and display extra bullet icons on the ammo count that doesn't update. They are tied to the weapon though as in switching weapons will make them go away but come back when I switch back to said weapon,  This has happened in two games on three weapons first game it happened about half-way through, the second game, it was as soon as I switched weapons. I'm unsure if this is a mod conflict going on though, I also have Goonmod and Pocohud installed, too.

**Comment by simon-wh** [comment]
I just pushed an update which should solve this issue, I'll leave this issue open for now until it is confirmed fixed (due to the difficulty of replicating the issue).
